services:
  - type: web
    name: mcmetsolart-site
    env: python
    region: frankfurt
    plan: free
    buildCommand: cd McMetSolArtBackend && pip install -r requirements.txt
    startCommand: cd McMetSolArtBackend && gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE
        value: mc_metsolart.db
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000
