build:
  - type: web
    name: mc-metsolart-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    staticPublishPath: ./
    envVars:
      - key: DATABASE
        value: /tmp/mc_metsolart.db
      - key: FLASK_DEBUG
        value: "False"
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: "8000"
      - key: EMAIL_ENABLED
        value: "False"
databases:
  - name: mc-metsolart-db
    databaseName: mc_metsolart
    plan: free
    postgreSQL: false
